### ISSUE TITLE
VC任务采用NS2的目的是啥

### ISSUE THREAD

**Issue by hdmjdp** [adelacvg/NS2VC#2]
如题

**Comment by adelacvg** [comment]
目前是为了zero shot VC。另一方面ns2和sd的结构很像，未来做各种条件生成改起来也要方便一些，理论上讲可玩性更强。

**Comment by adelacvg** [comment]
数据集足够大的话应该是能复现原论文demo的效果。已经在很小的数据集上过拟合验证了模型，目前正在用vctk训练。
