### ISSUE TITLE
four preprocessed assert

### ISSUE THREAD

**Issue by yiwei0730** [adelacvg/NS2VC#22]
lmin = min(f0.size(-1), spec.size(-1), sum(duration))
assert abs(f0.size(-1) - spec.size(-1)) < 3, (spec.size(-1), f0.shape, filename)
assert abs(spec.size(-1) - sum(duration)) < 3, (spec.size(-1), sum(duration), filename)
assert abs(audio.shape[1]- lmin * self.hop_length) < 3 * self.hop_length , (audio.shape[1], lmin, self.hop_length, filename)
assert phone.shape[0] == duration.shape[0]
能否幫我解惑一下 這四個assert 的含意是什麼

**Comment by yiwei0730** [comment]
還有一個似乎有在so-vits-vc上也有看過的使用方式，不知道這個計算是出自哪篇論文?
f0 = 2595. * torch.log10(1. + f0_padded.unsqueeze(1) / 700.) / 500

**Comment by adelacvg** [comment]
assert都是为了保证提取出的各个特征是对齐的，主要为了防止字典不全导致和dur序列无法对齐，一般相差1是正常的。f0的计算公式我是从sovits抄来的，并不知道出处。
