### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by PS-AI** [adelacvg/NS2VC#3]
Hi,

Thank you for your work.

I got this error:
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects
when trying to run :
pip install audiolm_pytorch

Please let me know how to fix this.

**Comment by adelacvg** [comment]
I had encountered this issue on a Windows system. I downloaded the dependencies for cpp dev and clang using `https://visualstudio.microsoft.com/visual-cpp-build-tools/`. Hope it can help you.

**Comment by PS-AI** [comment]
Thanks for the quick response. I am running it on Ubuntu. I used Python 3.8 and the problem did not occur.
